#!/bin/bash
echo "Custom Build Script Executing Now"
mvn -v
echo *** Environment Variables ***
env | grep OPENSHIFT
echo *** Launching MVN ***
echo cd $OPENSHIFT_REPO_DIR/diy
cd $OPENSHIFT_REPO_DIR/diy
echo Current Directory is ...
pwd
echo mvn package -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml -DskipTests=true
mvn package -X -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml -DskipTests=true
echo "Custom Build Script Execution Completed..!"