#!/bin/bash
echo "Custom Start Script Executing Now"

echo cd $OPENSHIFT_REPO_DIR
cd $OPENSHIFT_REPO_DIR

echo nohup java -jar $OPENSHIFT_REPO_DIR/target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &
nohup java -jar diy/target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &

echo "Custom Start Script Execution Kicked Off"
