#!/bin/bash
echo "Custom Start Script Executing Now"
cd $OPENSHIFT_REPO_DIR
nohup java -jar target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &
echo "Custom Start Script Execution Kicked Off"
