#!/bin/bash
echo "Custom Stop Script Executing Now"
source $OPENSHIFT_CARTRIDGE_SDK_BASH

PID=$(ps -ef | grep java.*\.jar | grep -v grep | awk '{ print $2 }')
if [ -z "$PID" ]
then
    client_result "Application is already stopped"
else
    kill $PID
fi
echo "Custom Stop Script Execution Complete!"
